export const OrderDetails = [
    {
        customerId: 1,
        orderId: 367,
        name: 'John Doe',
        city: 'New York',
        email: 'john.doe@example.com',
        mobileNumber: '1234567890',
        orderDate: '2022-01-01',
        address: 'ABC',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 2,
        orderId: 387,
        name: 'Jane Smith',
        city: 'Los Angeles',
        email: 'jane.smith@example.com',
        mobileNumber: '9876543210',
        orderDate: '2022-01-02',
        address: 'ABC',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 3,
        orderId: 1000,
        name: 'Alice Johnson',
        city: 'Chicago',
        email: 'alice.johnson@example.com',
        mobileNumber: '5551234567',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 4,
        orderId: 1001,
        name: 'Bob Williams',
        city: 'Houston',
        email: 'bob.williams@example.com',
        mobileNumber: '5559876543',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View ',
        status: 'Not Reviewed',
    },
    {
        customerId: 5,
        orderId: 1002,
        name: 'Eva Brown',
        city: 'Miami',
        email: 'eva.brown@example.com',
        mobileNumber: '5555678901',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View ',
        status: 'Reviewed',
    },
    {
        customerId: 6,
        orderId: 1003,
        name: 'David Lee',
        city: 'San Francisco',
        email: 'david.lee@example.com',
        mobileNumber: '5552223333',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 7,
        orderId: 1004,
        name: 'Grace Garcia',
        city: 'Dallas',
        email: 'grace.garcia@example.com',
        mobileNumber: '5554445555',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View ',
        status: 'Reviewed',
    },
    {
        customerId: 8,
        orderId: 1005,
        name: 'James Brown',
        city: 'Atlanta',
        email: 'james.brown@example.com',
        mobileNumber: '5556667777',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 9,
        orderId: 1006,
        name: 'Emily Miller',
        city: 'Denver',
        email: 'emily.miller@example.com',
        mobileNumber: '5558889999',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 10,
        orderId: 1007,
        name: 'Daniel Martinez',
        city: 'Phoenix',
        email: 'daniel.martinez@example.com',
        mobileNumber: '5551234567',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 11,
        orderId: 1008,
        name: 'Olivia Davis',
        city: 'Seattle',
        email: 'olivia.davis@example.com',
        mobileNumber: '5557654321',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 12,
        orderId: 1009,
        name: 'Andrew Wilson',
        city: 'Boston',
        email: 'andrew.wilson@example.com',
        mobileNumber: '5559876543',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 13,
        orderId: 1010,
        name: 'Sophia Taylor',
        city: 'Philadelphia',
        email: 'sophia.taylor@example.com',
        mobileNumber: '5552345678',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 14,
        orderId: 1011,
        name: 'William Anderson',
        city: 'San Diego',
        email: 'william.anderson@example.com',
        mobileNumber: '5558765432',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 15,
        orderId: 1012,
        name: 'Ava Thomas',
        city: 'Detroit',
        email: 'ava.thomas@example.com',
        mobileNumber: '5553456789',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 16,
        orderId: 1013,
        name: 'Alexander White',
        city: 'Minneapolis',
        email: 'alexander.white@example.com',
        mobileNumber: '5559876543',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 17,
        orderId: 1014,
        name: 'Mia Moore',
        city: 'Portland',
        email: 'mia.moore@example.com',
        mobileNumber: '5555678901',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 18,
        orderId: 1015,
        name: 'Henry Jackson',
        city: 'Las Vegas',
        email: 'henry.jackson@example.com',
        mobileNumber: '5552223333',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    },
    {
        customerId: 19,
        orderId: 1016,
        name: 'Victoria Harris',
        city: 'Orlando',
        email: 'victoria.harris@example.com',
        mobileNumber: '5554445555',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Reviewed',
    },
    {
        customerId: 20,
        orderId: 1017,
        name: 'Jackson Brown',
        city: 'Nashville',
        email: 'jackson.brown@example.com',
        mobileNumber: '5556667777',
        orderDate: '2024-03-30',
        address: 'XYZ',
        orderDetails: 'View',
        status: 'Not Reviewed',
    }
];


