export const ViewDetails = [
    {
      "id": 1,
      "image": "image1.jpg",
      "name": "Product A",
      "color": "Red",
      "size": "Medium",
      "price": 10.99,
      "quantity": 50,
      'status': 'Reviewed',
    },
    {
      "id": 2,
      "image": "image2.jpg",
      "name": "Product B",
      "color": "Blue",
      "size": "Large",
      "price": 19.99,
      "quantity": 30,
      'status': 'Reviewed',
    },
    {
      "id": 3,
      "image": "image3.jpg",
      "name": "Product C",
      "color": "Green",
      "size": "Small",
      "price": 8.50,
      "quantity": 20,
      'status': 'Reviewed',
    },
    {
      "id": 4,
      "image": "image4.jpg",
      "name": "Product D",
      "color": "Yellow",
      "size": "Medium",
      "price": 14.75,
      "quantity": 40,
      'status': 'Reviewed',
    },
    {
      "id": 5,
      "image": "image5.jpg",
      "name": "Product E",
      "color": "Black",
      "size": "Large",
      "price": 24.99,
      "quantity": 25,
      'status': 'Reviewed',
    },
    {
      "id": 6,
      "image": "image6.jpg",
      "name": "Product F",
      "color": "White",
      "size": "Small",
      "price": 12.00,
      "quantity": 35,
      'status': 'Reviewed',
    },
    {
      "id": 7,
      "image": "image7.jpg",
      "name": "Product G",
      "color": "Brown",
      "size": "Medium",
      "price": 18.50,
      "quantity": 15,
      'status': 'Reviewed',
    },
    {
      "id": 8,
      "image": "image8.jpg",
      "name": "Product H",
      "color": "Purple",
      "size": "Large",
      "price": 29.99,
      "quantity": 10,
      'status': 'Reviewed',
    },
    {
      "id": 9,
      "image": "image9.jpg",
      "name": "Product I",
      "color": "Orange",
      "size": "Small",
      "price": 9.99,
      "quantity": 60,
      'status': 'Reviewed',
    },
    {
      "id": 10,
      "image": "image10.jpg",
      "name": "Product J",
      "color": "Gray",
      "size": "Medium",
      "price": 16.50,
      "quantity": 45,
      'status': 'Reviewed',
    }
  ]
  